# Generated by Django 3.1.1 on 2021-04-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210415_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.CharField(default='Unknown', max_length=60),
        ),
    ]
